# Generated by Django 3.0.5 on 2020-05-03 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account', models.CharField(default='00000000000000000000000000', max_length=28)),
                ('beneficiary_account', models.CharField(default='00000000000000000000000000', max_length=28)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(choices=[(3, 'CHF'), (0, 'PLN'), (2, 'GBP'), (1, 'EUR')], max_length=3)),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('transfer_date', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 15, 37, 26, 370053, tzinfo=utc))),
            ],
        ),
    ]
